<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<script src="<?= $block->getViewFileUrl('Loqate_ApiIntegration::capture.js') ?>"></script>
<link href="<?= $block->getViewFileUrl('Loqate_ApiIntegration::capture.css') ?>" rel="stylesheet" type="text/css" />

<div id="loqate-urls"
     data-find-url="<?= $block->getUrl('loqate/capture/find'); ?>"
     data-retrieve-url="<?= $block->getUrl('loqate/capture/retrieve'); ?>">
</div>
